//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.01.17 at 02:48:31 PM NZDT
//
package de.leonhardt.sbm.smsbr.xml.model;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import lombok.Getter;
import lombok.Setter;

/**
 * <p>Mms from SMS backup & Restore</p>
 *
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="parts">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="part" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="seq" use="required" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                           &lt;attribute name="ct" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="chset" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="cd" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="fn" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="cid" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="cl" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="ctt_s" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="ctt_t" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="text" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="data" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="text_only" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *       &lt;attribute name="sub" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="retr_st" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="date" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *       &lt;attribute name="ct_cls" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sub_cs" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="read" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *       &lt;attribute name="ct_l" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tr_id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="st" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="msg_box" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *       &lt;attribute name="address" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="m_cls" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="d_tm" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="read_status" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ct_t" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="retr_txt_cs" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="d_rpt" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *       &lt;attribute name="m_id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="date_sent" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *       &lt;attribute name="seen" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *       &lt;attribute name="m_type" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *       &lt;attribute name="v" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *       &lt;attribute name="exp" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="pri" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *       &lt;attribute name="rr" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *       &lt;attribute name="resp_txt" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="rpt_a" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="locked" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *       &lt;attribute name="retr_txt" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="resp_st" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="m_size" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="readable_date" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="contact_name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Mms", propOrder = {
    "parts"
})
@XmlRootElement(name = "mms")
@Getter @Setter
public class Mms extends Message {

    @XmlElement(required = true)
    protected Mms.Parts parts;
    @XmlAttribute(name = "text_only")
    @XmlSchemaType(name = "unsignedByte")
    protected Short textOnly;
    @XmlAttribute(name = "sub")
    protected String sub;
    @XmlAttribute(name = "retr_st", required = true)
    protected String retrSt;
    @XmlAttribute(name = "ct_cls", required = true)
    protected String ctCls;
    @XmlAttribute(name = "sub_cs", required = true)
    protected String subCs;
    @XmlAttribute(name = "ct_l", required = true)
    protected String ctL;
    @XmlAttribute(name = "tr_id", required = true)
    protected String trId;
    @XmlAttribute(name = "st", required = true)
    protected String st;
    @XmlAttribute(name = "msg_box", required = true)
    @XmlSchemaType(name = "unsignedByte")
    protected short msgBox;
    @XmlAttribute(name = "address", required = true)
    protected long address;
    @XmlAttribute(name = "m_cls", required = true)
    protected String mCls;
    @XmlAttribute(name = "d_tm", required = true)
    protected String dTm;
    @XmlAttribute(name = "read_status", required = true)
    protected String readStatus;
    @XmlAttribute(name = "ct_t", required = true)
    protected String ctT;
    @XmlAttribute(name = "retr_txt_cs", required = true)
    protected String retrTxtCs;
    @XmlAttribute(name = "d_rpt", required = true)
    @XmlSchemaType(name = "unsignedByte")
    protected short dRpt;
    @XmlAttribute(name = "m_id", required = true)
    protected String mId;
    //@XmlAttribute(name = "date_sent", required = true)
    //@XmlSchemaType(name = "unsignedByte")
    //protected short dateSent;
    @XmlAttribute(name = "seen", required = true)
    @XmlSchemaType(name = "unsignedByte")
    protected short seen;
    @XmlAttribute(name = "m_type", required = true)
    @XmlSchemaType(name = "unsignedByte")
    protected short mType;
    @XmlAttribute(name = "v", required = true)
    @XmlSchemaType(name = "unsignedByte")
    protected short v;
    @XmlAttribute(name = "exp", required = true)
    protected String exp;
    @XmlAttribute(name = "pri", required = true)
    @XmlSchemaType(name = "unsignedByte")
    protected short pri;
    // XXX rr (read-report) should be an unsigned byte (boolean), but is sometimes null in exports
    @XmlAttribute(name = "rr", required = true)
    //@XmlSchemaType(name = "unsignedByte")"
    protected String rr;
    @XmlAttribute(name = "resp_txt", required = true)
    protected String respTxt;
    @XmlAttribute(name = "rpt_a", required = true)
    protected String rptA;
    @XmlAttribute(name = "locked", required = true)
    @XmlSchemaType(name = "unsignedByte")
    protected short locked;
    @XmlAttribute(name = "retr_txt", required = true)
    protected String retrTxt;
    @XmlAttribute(name = "resp_st", required = true)
    protected String respSt;
    @XmlAttribute(name = "m_size", required = true)
    protected String mSize;


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="part" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="seq" use="required" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                 &lt;attribute name="ct" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="chset" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="cd" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="fn" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="cid" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="cl" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="ctt_s" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="ctt_t" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="text" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="data" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "part"
    })
    public static class Parts {

        @XmlElement(required = true)
        protected List<Mms.Parts.Part> part;

        /**
         * Gets the value of the part property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the part property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPart().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Smses.Mms.Parts.Part }
         *
         *
         */
        public List<Mms.Parts.Part> getPart() {
            if (part == null) {
                part = new ArrayList<Mms.Parts.Part>();
            }
            return this.part;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="seq" use="required" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *       &lt;attribute name="ct" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="chset" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="cd" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="fn" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="cid" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="cl" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="ctt_s" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="ctt_t" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="text" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="data" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        @Getter @Setter
        public static class Part {

            @XmlAttribute(name = "seq", required = true)
            protected byte seq;
            @XmlAttribute(name = "ct", required = true)
            protected String ct;
            @XmlAttribute(name = "name", required = true)
            protected String name;
            @XmlAttribute(name = "chset", required = true)
            protected String chset;
            @XmlAttribute(name = "cd", required = true)
            protected String cd;
            @XmlAttribute(name = "fn", required = true)
            protected String fn;
            @XmlAttribute(name = "cid", required = true)
            protected String cid;
            @XmlAttribute(name = "cl", required = true)
            protected String cl;
            @XmlAttribute(name = "ctt_s", required = true)
            protected String cttS;
            @XmlAttribute(name = "ctt_t", required = true)
            protected String cttT;
            @XmlAttribute(name = "text", required = true)
            protected String text;
            @XmlAttribute(name = "data")
            protected String data;
        }

    }

}
